#ifndef RL_ASL_CONF_H
#define RL_ASL_CONF_H

#ifdef SRL_ASL_CONF_UNICAST_SLOTFRAME_HANDLE
#define RL_ASL_UNICAST_SLOTFRAME_HANDLE SRL_ASL_CONF_UNICAST_SLOTFRAME_HANDLE
#else
#define RL_ASL_UNICAST_SLOTFRAME_HANDLE 1
#endif /* SRL_ASL_CONF_UNICAST_SLOTFRAME_HANDLE */

#endif /* RL_ASL_CONF_H */