CONTIKI_PROJECT = orchestra
all: $(CONTIKI_PROJECT)

CONTIKI = ../../..

include $(CONTIKI)/Makefile.dir-variables
include $(CONTIKI)/examples/rl-asl/Makefile.rl-asl-include
include $(CONTIKI)/Makefile.include